#!/usr/bin/env bash
#
# Check for requirements and then hosts the website with `uvicorn` at port 8000

function log()
{
    color=$1
    message=$2

    case $color in
        green) echo "$(tput setaf 120)$(tput bold)--> $message$(tput sgr0)" && sleep 0.5;;
        red) echo "$(tput setaf 196)$(tput bold)--> $message$(tput sgr0)" && sleep 0.5;;
        *) return ;;
    esac
}

function start_application() 
{
    log "green" "starting application"
    exec uvicorn app.main:app --reload --port 8000
}

function create_virtual_environment()
{
    if python3 -m venv $SCRIPT_DIR/.venv; then 
      echo log "green" "virtual environment created at '$SCRIPT_DIR/.venv/'"
    else 
      log "red" "could not create virtual environment" && exit 1 
    fi
}

function install_requirements()
{
    source $VENV_IS_IN_PATH/activate
    
    if pip install -r $SCRIPT_DIR/requirements.txt; then
      log "green" "requirements installed"
    else
      log "red" "couldnot install requirements" && exit 1
    fi
}

function requirements_are_installed()
{
    while IFS= read -r package; do
        [[ -z "$package" || "$package" =~ ^# ]] && continue

        if ! pip show "$package" >/dev/null 2>&1; then
            return 1
        fi
    done < "$SCRIPT_DIR/requirements.txt"
    return 0 
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_ACTIVATE_PATH="$SCRIPT_DIR/.venv/bin/activate"
VENV_EXISTS=$VENV_ACTIVATE_PATH
VENV_BIN="$SCRIPT_DIR/.venv/bin"
VENV_IS_IN_PATH=$VENV_BIN

if [[ ! -f $VENV_EXISTS ]];then
    log "red" "virtual environment not detecting, creating virtual environment..."
    create_virtual_environment
    install_requirements
    start_application
else
    log "green" "virtual environment detected"
    case "$PATH:" in
        "$VENV_IS_IN_PATH:"*)
            log "green" "'.venv/bin/activate' is in PATH"
            if requirements_are_installed;then
                log "green" "requirements installed"
                start_application
            else
                log "red" "requirements not installed, installing..."
                install_requirements
                start_application
            fi ;;
        *)
            log "red" "'.venv/bin/activate' is not in PATH, consider running 'source .venv/bin/activate'"
            source $VENV_ACTIVATE_PATH
            if requirements_are_installed;then
                log "green" "requirements installed"
                start_application
            else
                log "red" "requirements not installed, installing..."
                install_requirements
                start_application
            fi ;;
        esac
fi
