#!/bin/sh
#
# Highlight NOTEs ,FIXMEs and TODOs around the source code

function usage() {
    echo "usage: $0 [note|notes|fixme]" && exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -eq 0 ]];then  
    rg --glob "!$SCRIPT_DIR/TODO" "TODO" $SCRIPT_DIR
else 
    case "$1" in 
        note|notes) rg --glob "!$SCRIPT_DIR/TODO" "NOTE" $SCRIPT_DIR ;;
        fixme) rg --glob "!$SCRIPT_DIR/TODO" "FIXME" $SCRIPT_DIR ;;
        *) usage ;;
    esac 
fi

