#!/bin/sh
#
# Tests the Webhook creation

curl  -X POST "http://localhost:8000/api/v1/webhooks/config" \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer aEaItIjAYmSt-hQbThtQf6LHE-rrg-hXcWUYFZG2D84"
      -d '{
        "webhook_url": "ngrok website etc"
      }'
