#!/usr/bin/env bash
#
# Tests the Vaquinha API user creation

curl --request POST \
     --url "http://127.0.0.1:8000/api/v1/users" \
     --header "Content-Type: application/json" \
     --header "Authorization: Bearer aEaItIjAYmSt-hQbThtQf6LHE-rrg-hXcWUYFZG2D84"
     --data '{
       "email": "gana@gmail.com",
       "name": "Guilherme Ganassini",
       "cpf": "44401970004"
     }'
