#!/bin/sh
#
# Tests the Webhook creation

curl  -X POST "http://localhost:8000/api/v1/webhooks/config" \
      -H "Content-Type: application/json" \
      -d '{
        "webhook_url": "https://localhost:8000/api/v1/webhooks/pix"
      }'
